// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClkBe9J4WXcUxd6ZG4tlJEvCE5uNMU3mU',
    appId: '1:296425154517:web:d965dc6ea4705cfff3bf5c',
    messagingSenderId: '296425154517',
    projectId: 'ljh-firebase-for-flutter',
    authDomain: 'ljh-firebase-for-flutter.firebaseapp.com',
    storageBucket: 'ljh-firebase-for-flutter.appspot.com',
    measurementId: 'G-MW19KEF9KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHXW4XTy7YjI8QXtUHnWmYCew4pRT3AQ',
    appId: '1:296425154517:android:d9a036705672eb4af3bf5c',
    messagingSenderId: '296425154517',
    projectId: 'ljh-firebase-for-flutter',
    storageBucket: 'ljh-firebase-for-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARf_ofKUQrLI_3a2D26QGeSUXGE3uv8k',
    appId: '1:296425154517:ios:0c94329ed3b9d604f3bf5c',
    messagingSenderId: '296425154517',
    projectId: 'ljh-firebase-for-flutter',
    storageBucket: 'ljh-firebase-for-flutter.appspot.com',
    iosBundleId: 'com.example.kumohbadaVer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDARf_ofKUQrLI_3a2D26QGeSUXGE3uv8k',
    appId: '1:296425154517:ios:48610941a8f4b45df3bf5c',
    messagingSenderId: '296425154517',
    projectId: 'ljh-firebase-for-flutter',
    storageBucket: 'ljh-firebase-for-flutter.appspot.com',
    iosBundleId: 'com.example.kumohbadaVer2.RunnerTests',
  );
}
